
# prefix will be prepended to all ressource names
variable "prefix" {
  type    = string
  default = "sample"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  default = "function_name"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  default = "function_handler_name"
}

# name of zip file to deploy, generated by 'mvn package' command
variable "zip_file_name" {
  type    = string
  default = "zip_file_name.zip"
}

variable "runtime" {
  type    = string
  default = "C#(.NET Core 6.0)"
}