# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  # default = "sample"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  # default = "function_name"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  # default = "function_handler_name"
}


# name of zip file to deploy, generated by 'dotnet build' command
variable "zip_file_local" {
  type    = string
  # default = "path/to/zip_file_name.zip"
}

variable "function_runtime" {
  type    = string
  # default = "C#(.NET Core 6.0)"
}

# Resource tag:
variable "tag_app_group" {
  type = string
  # default = "csharp-doc-sample-event-timer"
}

variable "API_GATEWAY_INSTANCE_ID" {
  type = string
  # default = "your_api_gateway_instance_id"
}

variable "use_swagger_ui" {
  type    = string
  default = "true"
}